### ISSUE TITLE
Weapon Imbue Issue

### ISSUE THREAD

**Issue by Markjmjr** [liquidbase/DuffedUIv9#25]
There is a bug when Flametongue Weapon is applied. First there is no duration in the buff bar, and second the UI keeps yelling Fatality.

**Comment by liquidbase** [comment]
What do you mean by Buff Bar? The class timer?
And if the UI says "Fatality", please have a look in the bug grabber / bug bag, because you will get a Lua error. Please post it here, as this will make it easier to isolate the error.

**Comment by liquidbase** [comment]
I have now tried to understand the problem. I did not receive a Lua error and the weapon buffs are not displayed in the class timer because they do not belong there with 60m.
In the buff display itself, the weapon buff is displayed accordingly (see screenshot).

### Weaponbuff present with timer
![Screenshot](https://i.imgur.com/Han14YA.jpeg)

### Tooltip of Weaponbuff
![Screenshot](https://i.imgur.com/yYW2UQk.jpeg)

**Comment by Markjmjr** [comment]
Try it with having both Imbues active. That's when I get the issues. If you still need the Lua I can grab it later after work.

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by liquidbase** [comment]
Okay I try it. The information was missing. But please still post the Lua error please.

**Comment by liquidbase** [comment]
Found the issue and workin on fix. Missed that enhancers can have two weapon enchants.

**Comment by liquidbase** [comment]
Issue is fixed with https://github.com/liquidbase/DuffedUIv9/commit/9cee3d4417d408339f83a9ebc3ef6111d51a1cd3
